- dubbo-api-docs/dubbo-api-docs-core/src/main/java/org/apache/dubbo/apidocs/core/DubboApiDocsAnnotationScanner.java
- dubbo-api-docs/dubbo-api-docs-core/src/main/java/org/apache/dubbo/apidocs/core/beans/ApiCacheItem.java
- dubbo-api-docs/dubbo-api-docs-core/src/main/java/org/apache/dubbo/apidocs/core/beans/ApiParamsCacheItem.java
- dubbo-api-docs/dubbo-api-docs-core/src/main/java/org/apache/dubbo/apidocs/core/beans/ModuleCacheItem.java
- dubbo-api-docs/dubbo-api-docs-core/src/main/java/org/apache/dubbo/apidocs/utils/ClassTypeUtil.java
- dubbo-api-docs/dubbo-api-docs-examples/examples-api/src/main/java/org/apache/dubbo/apidocs/examples/api/IQuickStartDemo.java
- dubbo-api-docs/dubbo-api-docs-examples/examples-api/src/main/java/org/apache/dubbo/apidocs/examples/params/QuickStartRequestBean.java
- dubbo-api-docs/dubbo-api-docs-examples/examples-api/src/main/java/org/apache/dubbo/apidocs/examples/params/QuickStartRespBean.java
- dubbo-api-docs/dubbo-api-docs-examples/examples-provider-sca/pom.xml
- dubbo-api-docs/dubbo-api-docs-examples/examples-provider/pom.xml
- dubbo-api-docs/dubbo-api-docs-examples/examples-provider/src/main/java/org/apache/dubbo/apidocs/examples/api/impl/QuickStartDemoImpl.java
新增quick start demo, 修改bug
新增quick start demo
修改bug
XXXXX
> 新增quick start demo, 修改bug

- dubbo-api-docs/codestyle/checkstyle.xml
- dubbo-api-docs/codestyle/dubbo_codestyle_for_idea.xml
- dubbo-api-docs/dubbo-api-docs-annotations/src/main/java/org/apache/dubbo/apidocs/annotations/ApiDoc.java
- dubbo-api-docs/dubbo-api-docs-annotations/src/main/java/org/apache/dubbo/apidocs/annotations/ApiModule.java
- dubbo-api-docs/dubbo-api-docs-core/src/main/java/org/apache/dubbo/apidocs/core/DubboApiDocsAnnotationScanner.java
- dubbo-api-docs/dubbo-api-docs-core/src/main/java/org/apache/dubbo/apidocs/core/beans/ApiParamsCacheItem.java
- dubbo-api-docs/dubbo-api-docs-core/src/main/java/org/apache/dubbo/apidocs/core/beans/HtmlTypeEnum.java
- dubbo-api-docs/dubbo-api-docs-core/src/main/java/org/apache/dubbo/apidocs/core/providers/DubboDocProviderImpl.java
- dubbo-api-docs/dubbo-api-docs-core/src/main/java/org/apache/dubbo/apidocs/utils/ClassTypeUtil.java
- dubbo-api-docs/dubbo-api-docs-examples/examples-api/src/main/java/org/apache/dubbo/apidocs/examples/api/IQuickStartDemo.java
- dubbo-api-docs/dubbo-api-docs-examples/examples-api/src/main/java/org/apache/dubbo/apidocs/examples/params/QuickStartRequestBase.java
- dubbo-api-docs/dubbo-api-docs-examples/examples-api/src/main/java/org/apache/dubbo/apidocs/examples/params/QuickStartRequestBean2.java
- dubbo-api-docs/dubbo-api-docs-examples/examples-api/src/main/java/org/apache/dubbo/apidocs/examples/params/QuickStartRespBean.java
- dubbo-api-docs/dubbo-api-docs-examples/examples-provider-sca/src/main/resources/application.yml
- dubbo-api-docs/dubbo-api-docs-examples/examples-provider-sca/src/main/resources/bootstrap.yml
- dubbo-api-docs/dubbo-api-docs-examples/examples-provider/pom.xml
- dubbo-api-docs/dubbo-api-docs-examples/examples-provider/src/main/java/org/apache/dubbo/apidocs/examples/api/impl/AsyncDemoImpl.java
- dubbo-api-docs/dubbo-api-docs-examples/examples-provider/src/main/java/org/apache/dubbo/apidocs/examples/api/impl/QuickStartDemoImpl.java
- dubbo-api-docs/dubbo-api-docs-examples/examples-provider/src/main/java/org/apache/dubbo/apidocs/examples/api/impl/SyncDemoImpl.java
- dubbo-api-docs/dubbo-api-docs-examples/examples-provider/src/main/java/org/apache/dubbo/apidocs/examples/spi/DubboDocExporterListener.java
- dubbo-api-docs/dubbo-api-docs-examples/examples-provider/src/main/java/org/apache/dubbo/apidocs/examples/spi/TestConfigInitializer.java
- dubbo-api-docs/dubbo-api-docs-examples/examples-provider/src/main/java/org/apache/dubbo/apidocs/examples/spi/TestConfigPostProcessor.java
- dubbo-api-docs/dubbo-api-docs-examples/examples-provider/src/main/resources/META-INF/dubbo/org.apache.dubbo.config.ConfigInitializer
- dubbo-api-docs/dubbo-api-docs-examples/examples-provider/src/main/resources/META-INF/dubbo/org.apache.dubbo.config.ConfigPostProcessor
- dubbo-api-docs/dubbo-api-docs-examples/examples-provider/src/main/resources/META-INF/dubbo/org.apache.dubbo.rpc.ExporterListener
- dubbo-api-docs/dubbo-api-docs-examples/examples-provider/src/main/resources/application.yml
- dubbo-api-docs/pom.xml
* fix #9  泛型问题
* fix #10 中的问题
* fix #7 增加BigDecimal, BigInteger的支持
* 增加 checkstyle 和 rat, 并修改对检查失败的地方
> Dubbo Api docs 多个问题修复

- .github/ISSUE_TEMPLATE/dubbo-spi-extensions-feature-request-template.md
- .github/ISSUE_TEMPLATE/dubbo-spi-extensions-issue-report-template.md
Add issue and feature template
> Add issue and feature template

- .github/ISSUE_TEMPLATE/dubbo-spi-extensions-feature-request-template.md
- .github/ISSUE_TEMPLATE/dubbo-spi-extensions-issue-report-template.md
> add issue template

- dubbo-api-docs/dubbo-api-docs-core/src/main/java/org/apache/dubbo/apidocs/core/Constants.java
- dubbo-api-docs/dubbo-api-docs-core/src/main/java/org/apache/dubbo/apidocs/core/DubboApiDocsAnnotationScanner.java
- dubbo-api-docs/dubbo-api-docs-core/src/main/java/org/apache/dubbo/apidocs/utils/ClassTypeUtil.java
- dubbo-api-docs/dubbo-api-docs-examples/examples-api/src/main/java/org/apache/dubbo/apidocs/examples/api/IQuickStartDemo.java
- dubbo-api-docs/dubbo-api-docs-examples/examples-api/src/main/java/org/apache/dubbo/apidocs/examples/params/QuickStartRequestBase.java
- dubbo-api-docs/dubbo-api-docs-examples/examples-provider/pom.xml
- dubbo-api-docs/dubbo-api-docs-examples/examples-provider/src/main/java/org/apache/dubbo/apidocs/examples/api/impl/QuickStartDemoImpl.java
- dubbo-api-docs/dubbo-api-docs-examples/examples-provider/src/main/resources/application.yml
> 解决 #16 中的泛型问题

- distribution/src/assembly/source-release.xml
- dubbo-api-docs/README.md
- dubbo-api-docs/README_ch.md
- pom.xml
release dubbo-api-docs 2.7.8.2
XXXXX
XXXXX
> release dubbo-api-docs 2.7.8.2

- distribution/pom.xml
- dubbo-api-docs/pom.xml
> release dubbo-api-docs-2.7.8.3

- dubbo-extensions-dependencies-bom/pom.xml
- pom.xml
> add denpendencies bom

- .codecov.yml
- dubbo-cluster-extensions/dubbo-cluster-broadcast-1/Readme.md
- dubbo-extensions-dependencies-bom/pom.xml
- pom.xml
> Add jacoco

- dubbo-cluster-extensions/dubbo-cluster-broadcast-1/pom.xml
- pom.xml
> Fix jacoco

- dubbo-serialization-extensions/dubbo-serialization-avro/pom.xml
- dubbo-serialization-extensions/dubbo-serialization-avro/src/main/java/org/apache/dubbo/common/serialize/avro/AvroObjectInput.java
- dubbo-serialization-extensions/dubbo-serialization-avro/src/main/java/org/apache/dubbo/common/serialize/avro/AvroObjectOutput.java
- dubbo-serialization-extensions/dubbo-serialization-avro/src/main/java/org/apache/dubbo/common/serialize/avro/AvroSerialization.java
- dubbo-serialization-extensions/dubbo-serialization-avro/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.common.serialize.Serialization
- dubbo-serialization-extensions/dubbo-serialization-test/pom.xml
- dubbo-serialization-extensions/dubbo-serialization-test/src/test/java/org/apache/dubbo/common/serialize/avro/AvroObjectInputOutputTest.java
- dubbo-serialization-extensions/dubbo-serialization-test/src/test/java/org/apache/dubbo/common/serialize/avro/AvroSerializationTest.java
- dubbo-serialization-extensions/dubbo-serialization-test/src/test/java/org/apache/dubbo/common/serialize/model/AnimalEnum.java
- dubbo-serialization-extensions/dubbo-serialization-test/src/test/java/org/apache/dubbo/common/serialize/model/BizException.java
- dubbo-serialization-extensions/dubbo-serialization-test/src/test/java/org/apache/dubbo/common/serialize/model/BizExceptionNoDefaultConstructor.java
- dubbo-serialization-extensions/dubbo-serialization-test/src/test/java/org/apache/dubbo/common/serialize/model/Organization.java
- dubbo-serialization-extensions/dubbo-serialization-test/src/test/java/org/apache/dubbo/common/serialize/model/Person.java
- dubbo-serialization-extensions/dubbo-serialization-test/src/test/java/org/apache/dubbo/common/serialize/model/SerializablePerson.java
- dubbo-serialization-extensions/dubbo-serialization-test/src/test/java/org/apache/dubbo/common/serialize/model/media/Image.java
- dubbo-serialization-extensions/dubbo-serialization-test/src/test/java/org/apache/dubbo/common/serialize/model/media/Media.java
- dubbo-serialization-extensions/dubbo-serialization-test/src/test/java/org/apache/dubbo/common/serialize/model/media/MediaContent.java
- dubbo-serialization-extensions/dubbo-serialization-test/src/test/java/org/apache/dubbo/common/serialize/model/person/BigPerson.java
- dubbo-serialization-extensions/dubbo-serialization-test/src/test/java/org/apache/dubbo/common/serialize/model/person/FullAddress.java
- dubbo-serialization-extensions/dubbo-serialization-test/src/test/java/org/apache/dubbo/common/serialize/model/person/PersonInfo.java
- dubbo-serialization-extensions/dubbo-serialization-test/src/test/java/org/apache/dubbo/common/serialize/model/person/PersonStatus.java
- dubbo-serialization-extensions/dubbo-serialization-test/src/test/java/org/apache/dubbo/common/serialize/model/person/Phone.java
- dubbo-serialization-extensions/dubbo-serialization-test/src/test/java/org/apache/dubbo/common/serialize/support/SerializableClassRegistryTest.java
- dubbo-serialization-extensions/dubbo-serialization-test/src/test/proto/GooglePB.proto
- dubbo-serialization-extensions/dubbo-serialization-test/src/test/resources/log4j.xml
- dubbo-serialization-extensions/dubbo-serialization-test/src/test/resources/org.apache.dubbo.common.serialize.dubbo/SimpleDO.fc
Make dubbo3 support avro serialization.
#54
> Extend avro serialization

- dubbo-mock-extensions/README.md
- dubbo-mock-extensions/README_ch.md
Fixes #69 
- add the English and Chinese Readme file.
XXXXX
> [ISSUE #69] add the readme file to dubbo-mock-extensions.

- dubbo-remoting-extensions/dubbo-remoting-quic/pom.xml
- dubbo-remoting-extensions/dubbo-remoting-quic/src/main/java/org/apache/dubbo/remoting/transport/quic/NettyCodecAdapter.java
- dubbo-remoting-extensions/dubbo-remoting-quic/src/main/java/org/apache/dubbo/remoting/transport/quic/QuicNettyBackedChannelBuffer.java
- dubbo-remoting-extensions/dubbo-remoting-quic/src/main/java/org/apache/dubbo/remoting/transport/quic/QuicNettyChannel.java
- dubbo-remoting-extensions/dubbo-remoting-quic/src/main/java/org/apache/dubbo/remoting/transport/quic/QuicNettyClient.java
- dubbo-remoting-extensions/dubbo-remoting-quic/src/main/java/org/apache/dubbo/remoting/transport/quic/QuicNettyClientHandler.java
- dubbo-remoting-extensions/dubbo-remoting-quic/src/main/java/org/apache/dubbo/remoting/transport/quic/QuicNettyEventLoopFactory.java
- dubbo-remoting-extensions/dubbo-remoting-quic/src/main/java/org/apache/dubbo/remoting/transport/quic/QuicNettyServer.java
- dubbo-remoting-extensions/dubbo-remoting-quic/src/main/java/org/apache/dubbo/remoting/transport/quic/QuicNettyServerHandler.java
- dubbo-remoting-extensions/dubbo-remoting-quic/src/main/java/org/apache/dubbo/remoting/transport/quic/QuicNettyTransporter.java
- dubbo-remoting-extensions/dubbo-remoting-quic/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.remoting.Transporter
> Add quic protocol support

- test/scenarios/scenarios-dubbo-serialization/dubbo-serialization-avro-test/pom.xml
- test/scenarios/scenarios-dubbo-serialization/dubbo-serialization-fastjson-test/pom.xml
- test/scenarios/scenarios-dubbo-serialization/dubbo-serialization-fst-test/pom.xml
- test/scenarios/scenarios-dubbo-serialization/dubbo-serialization-gson-test/pom.xml
- test/scenarios/scenarios-dubbo-serialization/dubbo-serialization-kryo-test/pom.xml
- test/scenarios/scenarios-dubbo-serialization/dubbo-serialization-protobuf-test/pom.xml
- test/scenarios/scenarios-dubbo-serialization/dubbo-serialization-protostuff-test/pom.xml
> fix scenarios version

- dubbo-rpc-extensions/dubbo-rpc-http/src/main/java/org/apache/dubbo/rpc/protocol/http/HttpProtocol.java
- dubbo-rpc-extensions/dubbo-rpc-webservice/src/main/java/org/apache/dubbo/rpc/protocol/webservice/WebServiceProtocol.java
> fix set protocol

- dubbo-configcenter-extensions/dubbo-configcenter-consul/pom.xml
- dubbo-configcenter-extensions/dubbo-configcenter-consul/src/main/java/org/apache/dubbo/configcenter/consul/ConsulConstants.java
- dubbo-configcenter-extensions/dubbo-configcenter-consul/src/main/java/org/apache/dubbo/configcenter/consul/ConsulDynamicConfiguration.java
- dubbo-configcenter-extensions/dubbo-configcenter-consul/src/main/java/org/apache/dubbo/configcenter/consul/ConsulDynamicConfigurationFactory.java
- dubbo-configcenter-extensions/dubbo-configcenter-consul/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.common.config.configcenter.DynamicConfigurationFactory
- dubbo-configcenter-extensions/dubbo-configcenter-consul/src/test/java/org/apache/dubbo/configcenter/consul/ConsulDynamicConfigurationTest.java
- dubbo-configcenter-extensions/dubbo-configcenter-etcd/pom.xml
- dubbo-configcenter-extensions/dubbo-configcenter-etcd/src/main/java/org/apache/dubbo/configcenter/support/etcd/EtcdDynamicConfiguration.java
- dubbo-configcenter-extensions/dubbo-configcenter-etcd/src/main/java/org/apache/dubbo/configcenter/support/etcd/EtcdDynamicConfigurationFactory.java
- dubbo-configcenter-extensions/dubbo-configcenter-etcd/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.common.config.configcenter.DynamicConfigurationFactory
- dubbo-configcenter-extensions/dubbo-configcenter-etcd/src/test/java/org/apache/dubbo/configcenter/support/etcd/EtcdDynamicConfigurationTest.java
- dubbo-configcenter-extensions/pom.xml
- dubbo-extensions-dependencies-bom/pom.xml
- dubbo-metadata-report-extensions/dubbo-metadata-report-consul/pom.xml
- dubbo-metadata-report-extensions/dubbo-metadata-report-consul/src/main/java/org/apache/dubbo/metadata/store/consul/ConsulMetadataReport.java
- dubbo-metadata-report-extensions/dubbo-metadata-report-consul/src/main/java/org/apache/dubbo/metadata/store/consul/ConsulMetadataReportFactory.java
- dubbo-metadata-report-extensions/dubbo-metadata-report-consul/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.metadata.report.MetadataReportFactory
- dubbo-metadata-report-extensions/dubbo-metadata-report-etcd/pom.xml
- dubbo-metadata-report-extensions/dubbo-metadata-report-etcd/src/main/java/org/apache/dubbo/metadata/store/etcd/EtcdMetadataReport.java
- dubbo-metadata-report-extensions/dubbo-metadata-report-etcd/src/main/java/org/apache/dubbo/metadata/store/etcd/EtcdMetadataReportFactory.java
- dubbo-metadata-report-extensions/dubbo-metadata-report-etcd/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.metadata.report.MetadataReportFactory
- dubbo-metadata-report-extensions/dubbo-metadata-report-etcd/src/test/java/org/apache/dubbo/metadata/store/etcd/EtcdMetadata4TstService.java
- dubbo-metadata-report-extensions/dubbo-metadata-report-etcd/src/test/java/org/apache/dubbo/metadata/store/etcd/EtcdMetadataReportTest.java
- dubbo-metadata-report-extensions/pom.xml
- Add consul config center
- Add consul metadata report
- Add etcd config center
- Add etcd metadata report
XXXXX
XXXXX
> Enhance configcenter & metadata-report modules

- dubbo-serialization-extensions/dubbo-serialization-protobuf/src/main/java/org/apache/dubbo/common/serialize/protobuf/support/GenericProtobufJsonObjectInput.java
- dubbo-serialization-extensions/dubbo-serialization-protobuf/src/main/java/org/apache/dubbo/common/serialize/protobuf/support/GenericProtobufJsonObjectOutput.java
- dubbo-serialization-extensions/dubbo-serialization-protobuf/src/main/java/org/apache/dubbo/common/serialize/protobuf/support/ProtobufAttachmentUtils.java
- dubbo-serialization-extensions/dubbo-serialization-protobuf/src/main/java/org/apache/dubbo/common/serialize/protobuf/support/ProtobufUtils.java
- dubbo-serialization-extensions/dubbo-serialization-protobuf/src/main/proto/MapValue.proto
> Fix protobuf json serialize object attachments

- dubbo-extensions-dependencies-bom/pom.xml
- dubbo-serialization-extensions/dubbo-serialization-kryo/src/main/java/org/apache/dubbo/common/serialize/kryo/utils/AbstractKryoFactory.java
- dubbo-serialization-extensions/dubbo-serialization-kryo/src/main/java/org/apache/dubbo/common/serialize/kryo/utils/PooledKryoFactory.java
- dubbo-serialization-extensions/dubbo-serialization-kryo/src/main/java/org/apache/dubbo/common/serialize/kryo/utils/ThreadLocalKryoFactory.java
- test/scenarios/scenarios-dubbo-serialization/dubbo-serialization-kryo-test/pom.xml
支持kryo 5.X版本 5.X解决了一些4.X的安全漏洞 性能也有所提升 维护也很活跃 4.X已经很久不维护了 最后提交时间是2018年
对原有插件做了5.X的适配
单测全部通过
XXXXX
> feature: support kryo 5.3.0

- dubbo-registry-extensions/dubbo-registry-nameservice/pom.xml
- dubbo-registry-extensions/dubbo-registry-nameservice/src/main/java/org/apache/dubbo/registry/nameservice/NameServiceRegistry.java
- dubbo-registry-extensions/dubbo-registry-nameservice/src/main/java/org/apache/dubbo/registry/nameservice/ServiceName.java
- dubbo-registry-extensions/dubbo-registry-nameservice/src/test/java/org/apache/dubbo/registry/nameservice/NameServiceRegistryFactoryTest.java
- dubbo-registry-extensions/dubbo-registry-nameservice/src/test/java/org/apache/dubbo/registry/nameservice/NameServiceRegistryTest.java
- dubbo-rpc-extensions/dubbo-rpc-rocketmq/pom.xml
- dubbo-rpc-extensions/dubbo-rpc-rocketmq/src/main/java/org/apache/dubbo/rpc/rocketmq/RocketMQChannel.java
- dubbo-rpc-extensions/dubbo-rpc-rocketmq/src/main/java/org/apache/dubbo/rpc/rocketmq/RocketMQExporter.java
- dubbo-rpc-extensions/dubbo-rpc-rocketmq/src/main/java/org/apache/dubbo/rpc/rocketmq/RocketMQInvoker.java
- dubbo-rpc-extensions/dubbo-rpc-rocketmq/src/main/java/org/apache/dubbo/rpc/rocketmq/RocketMQProtocol.java
- dubbo-rpc-extensions/dubbo-rpc-rocketmq/src/main/java/org/apache/dubbo/rpc/rocketmq/RocketMQProtocolConstant.java
- dubbo-rpc-extensions/dubbo-rpc-rocketmq/src/main/java/org/apache/dubbo/rpc/rocketmq/RocketMQProtocolServer.java
- dubbo-rpc-extensions/dubbo-rpc-rocketmq/src/main/java/org/apache/dubbo/rpc/rocketmq/codec/DecodeableRpcInvocation.java
- dubbo-rpc-extensions/dubbo-rpc-rocketmq/src/main/java/org/apache/dubbo/rpc/rocketmq/codec/RocketMQCodec.java
- dubbo-rpc-extensions/dubbo-rpc-rocketmq/src/main/java/org/apache/dubbo/rpc/rocketmq/codec/RocketMQCodecSupport.java
- dubbo-rpc-extensions/dubbo-rpc-rocketmq/src/main/java/org/apache/dubbo/rpc/rocketmq/codec/RocketMQCountCodec.java
- dubbo-rpc-extensions/dubbo-rpc-rocketmq/src/test/java/org/apache/dubbo/rpc/rocketmq/RocketMQChannelTest.java
- dubbo-rpc-extensions/dubbo-rpc-rocketmq/src/test/java/org/apache/dubbo/rpc/rocketmq/RocketMQExporterTest.java
- dubbo-rpc-extensions/dubbo-rpc-rocketmq/src/test/java/org/apache/dubbo/rpc/rocketmq/RocketMQInvokerTest.java
- dubbo-rpc-extensions/dubbo-rpc-rocketmq/src/test/java/org/apache/dubbo/rpc/rocketmq/RocketMQProtocolServerTest.java
- dubbo-rpc-extensions/dubbo-rpc-rocketmq/src/test/java/org/apache/dubbo/rpc/rocketmq/RocketMQProtocolTest.java
> Complete roketmq unit test

- dubbo-mock-extensions/README.md
- dubbo-mock-extensions/README_ch.md
> revert error description

- dubbo-cross-thread-extensions/README.md
- dubbo-cross-thread-extensions/pom.xml
- dubbo-cross-thread-extensions/src/main/java/org/apache/dubbo/crossthread/interceptor/RunnableOrCallableActivation.java
- dubbo-cross-thread-extensions/src/main/java/org/apache/dubbo/crossthread/interceptor/RunnableOrCallableConstructInterceptor.java
- dubbo-cross-thread-extensions/src/main/java/org/apache/dubbo/crossthread/interceptor/RunnableOrCallableMethodInterceptor.java
- dubbo-cross-thread-extensions/src/main/java/org/apache/dubbo/crossthread/toolkit/CallableWrapper.java
- dubbo-cross-thread-extensions/src/main/java/org/apache/dubbo/crossthread/toolkit/ConsumerWrapper.java
- dubbo-cross-thread-extensions/src/main/java/org/apache/dubbo/crossthread/toolkit/DubboCrossThread.java
- dubbo-cross-thread-extensions/src/main/java/org/apache/dubbo/crossthread/toolkit/FunctionWrapper.java
- dubbo-cross-thread-extensions/src/main/java/org/apache/dubbo/crossthread/toolkit/RunnableWrapper.java
- dubbo-cross-thread-extensions/src/test/java/org/apache/dubbo/crossthread/DubboCrossThreadTest.java
- dubbo-extensions-dependencies-bom/pom.xml
- pom.xml
fix https://github.com/apache/dubbo/issues/12656 12656
[AlbumenJ](https://github.com/AlbumenJ) suggest migrate https://github.com/apache/dubbo/pull/12657 to dubbo-api-extensions
add annotation @DubboCrossThread to copy dubbo.tag cross thread like my commit @TraceCrossThread in skywalking(https://github.com/apache/skywalking-java/commit/8612f80260c8dd691a5c8308625fae5fca03ade2),
with @DubboCrossThread , bute-buddy will auto copy dubbo.tag from parent thread to children thread .
new thread run to get dubbo.tag
in the …
> [Cross thread] tag corss thread by annotation

- README.md
- dobbo-doc-auto-gen/src/main/java/org/apache/dubbo/doc/DocAutoGen.java
> :memo: upgrade readme

- README.md
- dobbo-doc-auto-gen/src/main/java/org/apache/dubbo/doc/DocAutoGen.java
- dubbo-api-docs/README.md
- dubbo-api-docs/README_ch.md
- dubbo-api-docs/dubbo-api-docs-annotations/pom.xml
- dubbo-api-docs/dubbo-api-docs-core/pom.xml
- dubbo-api-docs/dubbo-api-docs-core/src/main/java/org/apache/dubbo/apidocs/core/DubboApiDocsAnnotationScanner.java
- dubbo-api-docs/dubbo-api-docs-examples/examples-api/pom.xml
- dubbo-api-docs/dubbo-api-docs-examples/examples-provider-sca/pom.xml
- dubbo-api-docs/dubbo-api-docs-examples/examples-provider/pom.xml
- dubbo-api-docs/dubbo-api-docs-examples/examples-provider/src/main/java/org/apache/dubbo/apidocs/examples/ExampleApplication.java
- dubbo-api-docs/dubbo-api-docs-examples/examples-provider/src/main/resources/application.yml
- dubbo-api-docs/dubbo-api-docs-examples/pom.xml
- dubbo-api-docs/pom.xml
> Upgrade32 api doc

- dubbo-configcenter-extensions/dubbo-configcenter-consul/pom.xml
- dubbo-configcenter-extensions/dubbo-configcenter-consul/src/test/java/org/apache/dubbo/configcenter/consul/ConsulDynamicConfigurationTest.java
> configcenter consul  support dubbo3.2

- dubbo-cluster-extensions/dubbo-cluster-loadbalance-peakewma/README.md
- dubbo-cluster-extensions/dubbo-cluster-loadbalance-peakewma/README_CN.md
- dubbo-cluster-extensions/dubbo-cluster-loadbalance-peakewma/pom.xml
> :arrow_up:  peakewma support dubbo3

- dubbo-remoting-extensions/dubbo-remoting-redis/src/main/java/org/apache/dubbo/remoting/redis/jedis/ClusterRedisClient.java
- dubbo-remoting-extensions/dubbo-remoting-redis/src/main/java/org/apache/dubbo/remoting/redis/jedis/MonoRedisClient.java
- dubbo-remoting-extensions/dubbo-remoting-redis/src/main/java/org/apache/dubbo/remoting/redis/jedis/SentinelRedisClient.java
Dubbo Redis register support select databases
XXXXX
XXXXX
> fix(#207): Dubbo Redis register support select databases

- dubbo-configcenter-extensions/dubbo-configcenter-etcd/src/test/java/org/apache/dubbo/configcenter/support/etcd/EtcdDynamicConfigurationTest.java
- dubbo-metadata-report-extensions/dubbo-metadata-report-etcd/pom.xml
- dubbo-registry-extensions/dubbo-registry-consul/src/test/java/org/apache/dubbo/registry/consul/ConsulServiceDiscoveryTest.java
- dubbo-registry-extensions/dubbo-registry-etcd3/pom.xml
- dubbo-registry-extensions/dubbo-registry-etcd3/src/test/java/org/apache/dubbo/registry/etcd/EtcdServiceDiscoveryTest.java
> registry center etcd support dubbo3.2

- README.md
- dobbo-doc-auto-gen/src/main/java/org/apache/dubbo/doc/DocAutoGen.java
> :memo: doc add release and reference

- .github/workflows/ci.yml
- .github/workflows/conformance.yml
> :green_heart: remove windows and add jdk17

- dubbo-remoting-extensions/dubbo-remoting-quic/pom.xml
- dubbo-remoting-extensions/dubbo-remoting-quic/src/main/java/org/apache/dubbo/remoting/transport/quic/QuicNettyServer.java
> :arrow_up: quic support dubbo3.2

- dubbo-rpc-extensions/dubbo-rpc-webservice/pom.xml
- dubbo-rpc-extensions/dubbo-rpc-webservice/src/main/java/org/apache/dubbo/rpc/protocol/webservice/WebServiceProtocol.java
> ⬆️ webservice upgrade dubbo3.2

- dubbo-extensions-dependencies-bom/pom.xml
- dubbo-remoting-extensions/dubbo-remoting-redis/src/main/java/org/apache/dubbo/remoting/redis/jedis/ClusterRedisClient.java
- dubbo-remoting-extensions/dubbo-remoting-redis/src/main/java/org/apache/dubbo/remoting/redis/jedis/MonoRedisClient.java
- dubbo-remoting-extensions/dubbo-remoting-redis/src/main/java/org/apache/dubbo/remoting/redis/jedis/SentinelRedisClient.java
- dubbo-rpc-extensions/dubbo-rpc-rocketmq/src/main/java/org/apache/dubbo/rpc/rocketmq/RocketMQInvoker.java
- dubbo-rpc-extensions/dubbo-rpc-rocketmq/src/main/java/org/apache/dubbo/rpc/rocketmq/codec/RocketMQCodec.java
- dubbo-serialization-extensions/dubbo-serialization-fury/pom.xml
- dubbo-serialization-extensions/dubbo-serialization-gson/src/main/java/org/apache/dubbo/common/serialize/gson/GsonJsonObjectOutput.java
- dubbo-serialization-extensions/dubbo-serialization-kryo/src/main/java/org/apache/dubbo/common/serialize/kryo/optimized/KryoObjectOutput2.java
- dubbo-serialization-extensions/dubbo-serialization-msgpack/src/main/java/org/apache/dubbo/common/serialize/msgpack/MsgpackObjectOutput.java
- dubbo-serialization-extensions/dubbo-serialization-protobuf/src/main/java/org/apache/dubbo/common/serialize/protobuf/support/GenericProtobufJsonObjectOutput.java
- dubbo-serialization-extensions/dubbo-serialization-protobuf/src/main/java/org/apache/dubbo/common/serialize/protobuf/support/GenericProtobufObjectOutput.java
upgrade dubbo to the latest 3.1.11 version in the `3.1.0` branch
apache/dubbo#13866
XXXXX
XXXXX
> upgrade dubbo to the 3.1 latest version in 3.1.0 branch

- dubbo-registry-extensions/dubbo-registry-dns/src/main/java/org/apache/dubbo/registry/dns/DNSServiceDiscovery.java
- dubbo-registry-extensions/dubbo-registry-dns/src/main/java/org/apache/dubbo/registry/dns/util/DNSResolver.java
- dubbo-registry-extensions/dubbo-registry-dns/src/test/java/org/apache/dubbo/registry/dns/DNSResolverTest.java
- pom.xml
fix #180 
1. fix netty resource leak in [issue comment description](https://github.com/apache/dubbo-spi-extensions/issues/180#issuecomment-1340658857) 
2. add try catch for `getInstance()`
1. fix netty resource leak
2. add try catch for `getInstance()`
XXXXX
unit-test and integration-test …
> fix: dubbo-registry-dns resource leak

- dubbo-cluster-extensions/dubbo-cluster-router-mesh/pom.xml
- dubbo-cluster-extensions/dubbo-cluster-router-mesh/src/test/resources/DestinationRuleTest.yaml
- dubbo-cluster-extensions/dubbo-cluster-router-mesh/src/test/resources/DestinationRuleTest2.yaml
- dubbo-cluster-extensions/dubbo-cluster-router-mesh/src/test/resources/VirtualServiceTest.yaml
- dubbo-extensions-dependencies-bom/pom.xml
- dubbo-remoting-extensions/dubbo-remoting-mina/src/test/java/org/apache/remoting/transport/mina/MinaClientToServerTest.java
- pom.xml
Many tests were not run due to the low junit api version
Two pom files were modified to update their versions
XXXXX
> fix test lib

- .github/dependabot.yaml
- .github/workflows/build-and-test-pr.yml
- .github/workflows/build-and-test-scheduled-3.1.yml
- .github/workflows/build-and-test-scheduled-3.2.yml
- .github/workflows/build-and-test-scheduled-main.yml
- .github/workflows/release-test.yml
apache/dubbo#13865
1. Prior to this, Unit testing only supported Ubuntu, add unit testing process for Windows platform
2. Add Dependabot config
1. Add CI workflow support unit test on Windows platform
2. Add Dependabot config
XXXXX
the [Software Donation …
> build: CI support unit test on Windows platform && Add Dependabot config

- dubbo-extensions-dependencies-bom/pom.xml
upgrade dubbo.version to 3.2.11
XXXXX
XXXXX
> upgrade dubbo.version to 3.2.11

- .mvn/wrapper/maven-wrapper.properties
- pom.xml
to fix this :
https://github.com/apache/dubbo-spi-extensions/pull/367
XXXXX
XXXXX
> upgrade maven version

- dubbo-configcenter-extensions/dubbo-configcenter-consul/src/test/java/org/apache/dubbo/configcenter/consul/ConsulDynamicConfigurationTest.java
- dubbo-extensions-dependencies-bom/pom.xml
Bump com.orbitz.consul:consul-client from 1.3.7 to 1.5.3
https://github.com/apache/dubbo-spi-extensions/pull/376
XXXXX
XXXXX
> Bump com.orbitz.consul:consul

- dubbo-extensions-dependencies-bom/pom.xml
- pom.xml
> :arrow_up: 3.0.0 release

- .github/workflows/build-and-test-pr.yml
- .github/workflows/build-and-test-scheduled-3.1.yml
- .github/workflows/release-test.yml
- dubbo-configcenter-extensions/dubbo-configcenter-etcd/pom.xml
- dubbo-configcenter-extensions/dubbo-configcenter-etcd/src/main/java/org/apache/dubbo/configcenter/support/etcd/EtcdDynamicConfiguration.java
- dubbo-configcenter-extensions/dubbo-configcenter-etcd/src/test/java/org/apache/dubbo/configcenter/support/etcd/EtcdDynamicConfigurationTest.java
- dubbo-extensions-dependencies-bom/pom.xml
- dubbo-metadata-report-extensions/dubbo-metadata-report-etcd/pom.xml
- dubbo-metadata-report-extensions/dubbo-metadata-report-etcd/src/test/java/org/apache/dubbo/metadata/store/etcd/EtcdMetadataReportTest.java
- dubbo-registry-extensions/dubbo-registry-etcd3/src/main/java/org/apache/dubbo/registry/etcd/EtcdCompatibleRegistryFactory.java
- dubbo-registry-extensions/dubbo-registry-etcd3/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.registry.RegistryFactory
- dubbo-registry-extensions/dubbo-registry-etcd3/src/test/java/org/apache/dubbo/registry/etcd/EtcdRegistryTest.java
- dubbo-remoting-extensions/dubbo-remoting-etcd3/pom.xml
- dubbo-remoting-extensions/dubbo-remoting-etcd3/src/test/java/org/apache/dubbo/remoting/etcd/jetcd/LeaseTest.java
* update jetcd version
* rename the dubbo-registry-etcd extension name from etcd3 to etcd
XXXXX
XXXXX
> Bump jetcd vertsion from 0.5.7 to 0.7.7

- README.md
- README_CN.md
> :memo: update 3.3 doc

- dubbo-extensions-dependencies-bom/pom.xml
- dubbo-proxy-extensions/dubbo-proxy-bytebuddy/pom.xml
- test/scenarios/scenarios-dubbo-serialization/dubbo-serialization-kryo-test/pom.xml
Bump dubbo.version from 3.2.13 to 3.2.14
to fix this https://github.com/apache/dubbo-spi-extensions/pull/430
XXXXX
> Bump dubbo.version from 3.2.13 to 3.2.14

- dubbo-serialization-extensions/dubbo-serialization-fastjson/src/test/java/org/apache/dubbo/common/serialize/fastjson/FastJsonObjectInputOutputTest.java
Add unit tests for Input and OutPut for dubbo-serialization-extensions/dubbo-serialization-fastjson modules. Refer https://github.com/apache/dubbo/issues/14394
This work is done by Tongyiling code:
1. Unit test class generation
2. Revise the test case with each adjustment question
3. Remove Chinese comments and generate English comments
Add unit tests with the help of Tonyiling code
exist. If the new feature or significant change is committed, …
> add FastJsonInOutTest

- dubbo-cluster-extensions/dubbo-cluster-broadcast-1/src/test/java/org/apache/dubbo/rpc/cluster/support/BroadcastCluster1InvokerTest.java
- dubbo-cluster-extensions/dubbo-cluster-broadcast-1/src/test/java/org/apache/dubbo/rpc/cluster/support/DemoService.java
Unit testing support for broadcast1 with tongyilingma refer here https://github.com/apache/dubbo/issues/14394
XXXXX
> Add cluster-broadcast1 unit test

- dubbo-serialization-extensions/dubbo-serialization-jdk/pom.xml
refer here https://github.com/apache/dubbo/pull/14408
hessian-lite optional set to true
XXXXX
> hessian-lite optional set to true

- dubbo-gateway-extensions/dubbo-gateway-consumer/src/test/java/org/apache/dubbo/gateway/consumer/test/OmnSerFilterTest.java
- dubbo-gateway-extensions/dubbo-gateway-consumer/src/test/java/org/apache/dubbo/gateway/consumer/test/Person.java
- dubbo-gateway-extensions/dubbo-gateway-consumer/src/test/resources/security/serialize.allowlist
add dubbo-gateway-extensions/dubbo-gateway-consumer unit test with Tongyilingma refer here https://github.com/apache/dubbo/issues/14394
XXXXX
> add consumer gateway test

- dubbo-extensions-dependencies-bom/pom.xml
set the bom flatten model to be consistent with Dubbo main library
XXXXX
XXXXX
> feat:set bom flatten model

- dubbo-metadata-report-extensions/dubbo-metadata-report-redis/pom.xml
- dubbo-metadata-report-extensions/dubbo-metadata-report-redis/src/main/java/org/apache/dubbo/metadata/store/redis/RedisMetadataReport.java
- dubbo-metadata-report-extensions/dubbo-metadata-report-redis/src/main/java/org/apache/dubbo/metadata/store/redis/RedisMetadataReportFactory.java
- dubbo-metadata-report-extensions/dubbo-metadata-report-redis/src/main/resources/META-INF/dubbo/internal/org.apache.dubbo.metadata.report.MetadataReportFactory
- dubbo-metadata-report-extensions/dubbo-metadata-report-redis/src/test/java/org/apache/dubbo/metadata/store/redis/RedisMetadata4TstService.java
- dubbo-metadata-report-extensions/dubbo-metadata-report-redis/src/test/java/org/apache/dubbo/metadata/store/redis/RedisMetadataReportTest.java
- dubbo-metadata-report-extensions/dubbo-metadata-report-redis/src/test/resources/log4j2-test.xml
- dubbo-metadata-report-extensions/pom.xml
Import metadata-report-redis implementation from Dubbo 3.3
Import metadata-report-redis implementation from Dubbo 3.3
> Import metadata-report-redis implementation from Dubbo 3.3

- dubbo-extensions-dependencies-bom/pom.xml
- dubbo-serialization-extensions/dubbo-serialization-fury/pom.xml
- dubbo-serialization-extensions/dubbo-serialization-fury/src/main/java/org/apache/dubbo/common/serialize/fury/dubbo/BaseFurySerialization.java
- dubbo-serialization-extensions/dubbo-serialization-fury/src/main/java/org/apache/dubbo/common/serialize/fury/dubbo/FuryCheckerListener.java
- dubbo-serialization-extensions/dubbo-serialization-fury/src/main/java/org/apache/dubbo/common/serialize/fury/dubbo/FuryCompatibleSerialization.java
- dubbo-serialization-extensions/dubbo-serialization-fury/src/main/java/org/apache/dubbo/common/serialize/fury/dubbo/FuryObjectInput.java
- dubbo-serialization-extensions/dubbo-serialization-fury/src/main/java/org/apache/dubbo/common/serialize/fury/dubbo/FuryObjectOutput.java
- dubbo-serialization-extensions/dubbo-serialization-fury/src/main/java/org/apache/dubbo/common/serialize/fury/dubbo/FurySerialization.java
- dubbo-serialization-extensions/dubbo-serialization-fury/src/test/java/org/apache/dubbo/common/serialize/fury/FuryObjectInputTest.java
- dubbo-serialization-extensions/dubbo-serialization-fury/src/test/java/org/apache/dubbo/common/serialize/fury/FuryObjectOutputTest.java
- dubbo-serialization-extensions/dubbo-serialization-fury/src/test/java/org/apache/dubbo/common/serialize/fury/FurySerializationTest.java
update apache-fury version to improve performance
update dependency version and add test-case
No
> update apache-fury version to improve performance

- dubbo-filter-extensions/dubbo-filter-seata/src/main/java/org/apache/dubbo/seata/SeataTransactionPropagationProviderFilter.java
XXXXX
fix issue: https://github.com/apache/dubbo/issues/14485
XXXXX
> fix lose seata xid when happens injvm invoke

- dubbo-metadata-report-extensions/dubbo-metadata-report-redis/src/main/java/org/apache/dubbo/metadata/store/redis/RedisMetadataReport.java
`listeners.get(msg).isEmpty()` Null pointer reported an error
`listeners.get(msg).isEmpty()` Null pointer reported an error
XXXXX
XXXXX
> `listeners.get(msg).isEmpty()` Null pointer reported an error

- .github/workflows/conformance.yml
- dubbo-extensions-dependencies-bom/pom.xml
- dubbo-metadata-report-extensions/dubbo-metadata-report-redis/pom.xml
- dubbo-registry-extensions/dubbo-registry-redis/src/test/java/org/apache/dubbo/registry/redis/RedisRegistryTest.java
- dubbo-remoting-extensions/dubbo-remoting-redis/src/main/java/org/apache/dubbo/remoting/redis/jedis/ClusterRedisClient.java
- dubbo-remoting-extensions/dubbo-remoting-redis/src/main/java/org/apache/dubbo/remoting/redis/support/AbstractRedisClient.java
Bump Jedis version from 3.10.0 to 5.1.0
Bump Jedis version from 3.10.0 to 5.1.0
> Bump Jedis version from 3.10.0 to 5.1.0

- dubbo-api-docs/dubbo-api-docs-examples/examples-provider/pom.xml
- dubbo-extensions-dependencies-bom/pom.xml
replace dubbo-dependencies-zookeeper to dubbo-dependencies-zookeeper-curator5
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not find artifact org.apache.dubbo:dubbo-dependencies-zookeeper:pom:3.3.0-beta.6-SNAPSHOT in apache.snapshots.https (https://repository.apache.org/content/repositories/snapshots) @ org.apache.dubbo.extensions:dubbo-extensions-dependencies-bom:3.3.0, /home/bigdata/.m2/repository/org/apache/dubbo/extensions/dubbo-extensions-dependencies-bom/3.3.0/dubbo-extensions-dependencies-bom-3.3.0.pom, line 175, column 19
@ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.apache.dubbo:dubbo-samples-serialization-java-3.3:1.0-SNAPSHOT …
> replace dubbo-dependencies-zookeeper to dubbo-dependencies-zookeeper-curator5

- dubbo-api-docs/dubbo-api-docs-examples/examples-provider-sca/pom.xml
- dubbo-api-docs/dubbo-api-docs-examples/examples-provider/pom.xml
- dubbo-extensions-dependencies-bom/pom.xml
- dubbo-filter-extensions/dubbo-filter-seata/pom.xml
- dubbo-filter-extensions/dubbo-filter-seata/src/main/java/org/apache/dubbo/seata/SeataTransactionPropagationConsumerFilter.java
- dubbo-filter-extensions/dubbo-filter-seata/src/main/java/org/apache/dubbo/seata/SeataTransactionPropagationProviderFilter.java
- dubbo-filter-extensions/dubbo-filter-seata/src/test/java/org/apache/dubbo/seata/SeataTransactionPropagationConsumerFilterTest.java
- dubbo-filter-extensions/dubbo-filter-seata/src/test/java/org/apache/dubbo/seata/SeataTransactionPropagationProviderFilterTest.java
> support apache seata 2.1.0

- dubbo-cluster-extensions/dubbo-cluster-broadcast-1/src/test/java/org/apache/dubbo/rpc/cluster/support/BroadcastCluster1InvokerTest.java
> fix-broadcast-test-unit

- README.md
- README_CN.md
- dubbo-api-docs/README.md
- dubbo-api-docs/README_ch.md
- dubbo-build-tools/pom.xml
- dubbo-build-tools/src/main/resources/checkstyle-header.txt
- dubbo-extensions-dependencies-bom/pom.xml
- dubbo-metadata-report-extensions/dubbo-metadata-rest/pom.xml
- dubbo-metadata-report-extensions/dubbo-metadata-rest/src/main/java/org/apache/dubbo/metadata/extension/rest/annotation/processing/jaxrs/JAXRSServiceRestMetadataResolver.java
- dubbo-metadata-report-extensions/dubbo-metadata-rest/src/main/java/org/apache/dubbo/metadata/extension/rest/api/jaxrs/JAXRSServiceRestMetadataResolver.java
- dubbo-rpc-extensions/dubbo-rpc-hessian/pom.xml
- dubbo-rpc-extensions/dubbo-rpc-http/pom.xml
- dubbo-rpc-extensions/dubbo-rpc-native-thrift/pom.xml
- dubbo-rpc-extensions/dubbo-rpc-redis/pom.xml
- dubbo-rpc-extensions/dubbo-rpc-rest/pom.xml
- dubbo-rpc-extensions/dubbo-rpc-rocketmq/src/main/java/org/apache/dubbo/rpc/rocketmq/codec/DecodeableRpcInvocation.java
- dubbo-rpc-extensions/dubbo-rpc-webservice/pom.xml
> upgrade doc version

- dubbo-extensions-dependencies-bom/pom.xml
Update apache fury version to 0.9.0
Update apache fury version to 0.9.0
> Update apache fury version to 0.9.0

- dubbo-serialization-extensions/dubbo-serialization-fury/src/main/java/org/apache/dubbo/common/serialize/fury/dubbo/FuryCompatibleSerialization.java
- dubbo-serialization-extensions/dubbo-serialization-fury/src/main/java/org/apache/dubbo/common/serialize/fury/dubbo/FurySerialization.java
enable fury string compression
enable fury string compression
XXXXX
> enable fury string compression

- .github/workflows/build-and-test-pr.yml
- .github/workflows/build-and-test-scheduled-3.3.yml
* upgrade doc version
* fix 3.3.1 bug
* fix TripleConstants import not found
* update doc
* pr add Support long paths on Windows
---------
XXXXX
XXXXX
XXXXX
> 3.3.1 (#566)

- .mvn/jvm.config
- dubbo-api-docs/README.md
- dubbo-api-docs/README_ch.md
- dubbo-api-docs/dubbo-api-docs-examples/examples-provider/pom.xml
- dubbo-extensions-dependencies-bom/pom.xml
- dubbo-metadata-report-extensions/dubbo-metadata-rest/pom.xml
- dubbo-metadata-report-extensions/dubbo-metadata-rest/src/main/java/org/apache/dubbo/metadata/extension/rest/annotation/processing/jaxrs/JAXRSServiceRestMetadataResolver.java
- dubbo-metadata-report-extensions/dubbo-metadata-rest/src/main/java/org/apache/dubbo/metadata/extension/rest/api/jaxrs/JAXRSServiceRestMetadataResolver.java
- dubbo-rpc-extensions/dubbo-rpc-hessian/pom.xml
- dubbo-rpc-extensions/dubbo-rpc-http/pom.xml
- dubbo-rpc-extensions/dubbo-rpc-native-thrift/pom.xml
- dubbo-rpc-extensions/dubbo-rpc-redis/pom.xml
- dubbo-rpc-extensions/dubbo-rpc-rest/pom.xml
- dubbo-rpc-extensions/dubbo-rpc-rocketmq/src/main/java/org/apache/dubbo/rpc/rocketmq/codec/DecodeableRpcInvocation.java
- dubbo-rpc-extensions/dubbo-rpc-webservice/pom.xml
- dubbo-serialization-extensions/dubbo-serialization-jdk/pom.xml
- pom.xml
1. update dubbo version to 3.3.4
2. remove dubbo-dependencies-zookeeper-curator5 which have been deleted from latest dubbo.
3. remove dubbo-remoting-zookeeper.
4. depend dubbo-serialization-jdk, dubbo-remoting-http with new group id: org.apache.dubbo.extensions.
5. import RestMetadataConstants with new package name.
6. import TripleConstants instead of TripleConstant.
7. depend hessian-lite of org.apache.dubbo instead of com.alibaba to avoid conflict problem, see details at https://github.com/apache/dubbo/actions/runs/15263954530/job/42926652437
XXXXX
XXXXX
just this issue, without pulling in …
> update dubbo version to 3.3.4

- README.md
> change README.md use the right icon url.

- dubbo-metadata-report-extensions/dubbo-metadata-report-redis/src/main/java/org/apache/dubbo/metadata/store/redis/RedisMetadataReport.java
related to https://github.com/apache/dubbo/issues/15411
XXXXX
XXXXX
XXXXX
> fix Refer to the zk implementation class Some methods should not be out of date Resulting in metadata not found issue

- dubbo-registry-extensions/dubbo-registry-consul/src/main/java/org/apache/dubbo/registry/consul/AbstractConsulRegistry.java
- dubbo-remoting-extensions/dubbo-remoting-etcd3/src/test/java/org/apache/dubbo/remoting/etcd/jetcd/LeaseTest.java
- dubbo-rpc-extensions/dubbo-rpc-rmi/src/main/java/com/alibaba/dubbo/rpc/protocol/rmi/RmiRemoteInvocation.java
- dubbo-serialization-extensions/dubbo-serialization-fory/src/main/java/org/apache/dubbo/common/serialize/fory/dubbo/BaseForySerialization.java
- dubbo-serialization-extensions/dubbo-serialization-fory/src/main/java/org/apache/dubbo/common/serialize/fory/dubbo/ForyCompatibleSerialization.java
- dubbo-serialization-extensions/dubbo-serialization-fory/src/main/java/org/apache/dubbo/common/serialize/fory/dubbo/ForyObjectOutput.java
- dubbo-serialization-extensions/dubbo-serialization-fory/src/main/java/org/apache/dubbo/common/serialize/fory/dubbo/ForySerialization.java
- dubbo-serialization-extensions/dubbo-serialization-fury/src/main/java/org/apache/dubbo/common/serialize/fury/dubbo/BaseFurySerialization.java
- dubbo-serialization-extensions/dubbo-serialization-fury/src/main/java/org/apache/dubbo/common/serialize/fury/dubbo/FuryCompatibleSerialization.java
- dubbo-serialization-extensions/dubbo-serialization-fury/src/main/java/org/apache/dubbo/common/serialize/fury/dubbo/FuryObjectOutput.java
- dubbo-serialization-extensions/dubbo-serialization-fury/src/main/java/org/apache/dubbo/common/serialize/fury/dubbo/FurySerialization.java
> Remove author info to align with license requirements
